### ISSUE TITLE
proposal to rename the mgem

### ISSUE THREAD

**Issue by bovi** [schmurfy/host-stats#1]
Hi,

I have a really pedantic request. Is it possible that we rename your mgem to something starting with "mruby-"? Maybe mruby-stats or mruby-hoststats? I remember your gem was one of the very early ones when we didn't yet have introduced a guideline to streamline mgem names. Evertime I update our global gem list I fall over this gem as it falls out of the structure (-;

/daniel

**Comment by schmurfy** [comment]
it did not have mruby in its name initally because it works with both MRI and mruby but I have no problem renaming it, I will have a look.

**Comment by schmurfy** [comment]
if I keep the repository name and only changes the mruby name would that solve the issue ?

**Comment by bovi** [comment]
yes, the repository name does not matter. if you just change the name in the mrbgems config that would be streamlining it. thanks for your response!

**Comment by schmurfy** [comment]
it's done :)

**Comment by bovi** [comment]
thanks!
